# fly.toml app configuration file generated for shoveler on 2024-09-27T07:15:06-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'navalogue'
primary_region = 'phx'
console_command = '/code/manage.py shell'

[build]
dockerfile = "docker/Dockerfile"

[deploy]
# entrypoint is /opt/venv/bin/python /appshoveler/manage.py
release_command = 'migrate --noinput'

[env]
PORT = '8000'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[statics]]
guest_path = '/code/static'
url_prefix = '/static/'
