# Generated by Django 5.1.2 on 2024-10-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="summary",
            field=models.TextField(default=""),
        ),
    ]
