# Generated by Django 5.1.2 on 2024-10-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblog", "0002_alter_entry_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="posttype",
            field=models.CharField(
                choices=[("post", "Post"), ("note", "Note")],
                default="post",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/uploads/"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
